site_name: MemoryStore API Docs

markdown_extensions:
  - admonition


nav:
  - About:
      - About: about.md
      - MemoryStore: index.md
  - Documentation:
      - API: API.md
      - Experimental: EXP.md