site_name: MemoryStore API Docs

markdown_extensions:
  - admonition


nav:
  - About:
      - About: about.md
      - Changelog: changelog.md
      - MemoryStore: index.md
  - Documentation:
      - API: API.md
      - Experimental: EXP.md
  - Help!:
      - Errors Explained: errorsexpl.md
      - How Do I?: howdoi.md